import React, {Component} from 'react'
import {createStore} from 'redux'
import {Provider} from 'react-redux'
import TabNav from './screens/tab.js'

const initialState={uhl:0,talk:0,gotItem:0,health:0,itemPic:null,ins:"Your friend is not feeling well. Talk to him.",item:Math.floor(Math.random()*100)%3,animal:Math.floor(Math.random()*100)%3,up:require("./images/KeyboardKeyUp.png"),down:require("./images/KeyboardKeyDown.png"),right:require("./images/KeyboardKeyRight.png"),left:require("./images/KeyboardKeyLeft.png"),DRest:require("./images/DRest.png"),DWalk1:require("./images/DWalk1.png"),DWalk2:require("./images/DWalk2.png"),FRest:require("./images/FRest.png"),FWalk1:require("./images/FWalk1.png"),FWalk2:require("./images/FWalk2.png"),LRest:require("./images/LRest.png"),LWalk1:require("./images/LWalk1.png"),LWalk2:require("./images/LWalk2.png"),RRest:require("./images/RRest.png"),RWalk1:require("./images/RWalk1.png"),RWalk2:require("./images/RWalk2.png"),Tree:require("./images/Tree.png"),kekadu:require("./images/DRest.png"),Banana:require("./images/Banana.png"),Carrot:require("./images/Carrot.png"),Medicine:require("./images/Medicine.png"),
DBird:require("./images/spriteart/DBird.png"),FBird:require("./images/spriteart/FBird.png"),LBird:require("./images/spriteart/LBird.png"),RBird:require("./images/spriteart/RBird.png"),DDonkey:require("./images/spriteart/DDonkey.png"),FDonkey:require("./images/spriteart/FDonkey.png"),LDonkey:require("./images/spriteart/LDonkey.png"),RDonkey:require("./images/spriteart/RDonkey.png"),DMonkey:require("./images/spriteart/DMonkey.png"),FMonkey:require("./images/spriteart/FMonkey.png"),LMonkey:require("./images/spriteart/LMonkey.png"),RMonkey:require("./images/spriteart/RMonkey.png"),DRabbit:require("./images/spriteart/DRabbit.png"),FRabbit:require("./images/spriteart/FRabbit.png"),LRabbit:require("./images/spriteart/LRabbit.png"),RRabbit:require("./images/spriteart/RRabbit.png"),DFox:require("./images/spriteart/DFox.png"),FFox:require("./images/spriteart/FFox.png"),LFox:require("./images/spriteart/LFox.png"),RFox:require("./images/spriteart/RFox.png"),
BananaTree:require("./images/BananaTree.png"),BirdFace:require("./images/BirdFace.jpg"),DonkeyFace:require("./images/DonkeyFace.png"),Jungle:require("./images/JungleBackgroundForGames.jpg"),Rock:require("./images/Rock.png"),Paper:require("./images/paper.png"),Scissor:require("./images/Scissor.png"),Question:require("./images/QuestionMark.png"),Happy:require("./images/to process/HappyRabbit.jpg"),Hungry:require("./images/to process/HungryRabbit.jpg"),Hit:require("./images/to process/HitRabbit.jpg"),Thermo:require("./images/to process/ThermoRabbit.jpg"),
BananaCount:0,CarrotCount:0,MedicineCount:0,x:160,y:160}
const reducer=(state=initialState,action)=>{switch(action.type){
case 'uh':
return{uhl:state.uhl+1,talk:state.talk+1,gotItem:0,health:state.health,itemPic:null,ins:state.ins,item:state.item,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:0,x:state.x,y:state.y}
case 'new':
if(state.item==0){return{uhl:state.uhl,talk:state.talk+1,gotItem:0,health:state.health,itemPic:null,ins:"Get a banana for your friend",item:state.item,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:0,x:state.x,y:state.y}}
if(state.item==1){return{uhl:state.uhl,talk:state.talk+1,gotItem:0,health:state.health,itemPic:null,ins:"Get a carrot for your friend",item:state.item,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:0,x:state.x,y:state.y}}
return{uhl:state.uhl,talk:state.talk+1,gotItem:0,health:state.health,itemPic:null,ins:"Get medicine for your friend",item:state.item,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:0,x:state.x,y:state.y}
case 'Update_Health':
if(state.item==0){
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.Thermo,itemPic:state.itemPic,ins:"Get a banana for your friend",item:state.item+1,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
if(state.item==1){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.Hungry,itemPic:state.itemPic,ins:"Get a carrot for your friend",item:state.item+1,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
if(state.item==2){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.Hit,itemPic:state.itemPic,ins:"Get medicine for your friend",item:0,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.Happy,itemPic:state.itemPic,ins:"Get a carrot for your friend",item:state.item+1,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}
case 'Go_Left1':
if(state.x<16){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}
case 'Go_Up1':
if(state.y<16){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y+304}}
if(state.y>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y-304}}
if(state.x>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Up2':
if(state.y>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y-304}}
if(state.y<16){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y+304}}
if(state.x>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Up3':
if(state.y>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y-304}}
if(state.y<304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y+304}}
if(state.x>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Up4':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y+304}
case 'Go_Up1Left1':
if(state.x>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Up1Left2':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Up2Left1':
if(state.x>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Up2Left2':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Up3Left1':
if(state.x>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Up3Left2':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Up1Right1':
if(state.x>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Up1Right2':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}
case 'Go_Up2Right2':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}
case 'Go_Up3Right2':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}
case 'Go_Up2Right1':
if(state.x>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Up3Right1':
if(state.x>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Left3':
if(state.x<16){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}
case 'Go_Left4':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_Monkey':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y-304}
case 'Go_Donkey':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y+304}
case 'Go_Left2':
if(state.x>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}}
if(state.y>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y-304}}
if(state.y<16){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y+304}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+304,y:state.y}
case 'Go_FriendScreen':
if(state.y>304){return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y-304}}
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-304,y:state.y}
case 'kleft':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x-16,y:state.y}
case 'kright':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x+16,y:state.y}
case 'kup':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y-16}
case 'kdown':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem,health:state.health,itemPic:state.itemPic,ins:state.ins,item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y+16}
//change below
case 'Get_Banana':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem+1,health:state.health,itemPic:state.Banana,ins:"Give the banana to your friend",item:state.item,animal:state.item,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:1,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y}
case 'Give_Banana':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem-1,health:state.health+1,itemPic:null,ins:"Get a carrot for your friend",item:state.item+1,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:0,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:state.x,y:state.y}
case 'Get_Carrot':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem+1,health:state.health,itemPic:state.Carrot,ins:"Give the carrot to your friend",item:state.item,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:1,MedicineCount:state.MedicineCount,x:state.x,y:state.y}
case 'Give_Carrot':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem-1,health:state.health+1,itemPic:null,ins:"Get medicine for your friend",item:state.item+1,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:0,MedicineCount:state.MedicineCount,x:state.x,y:state.y}
case 'Get_Medicine':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem+1,health:state.health+1,itemPic:state.Medicine,ins:"Give the medicine to your friend",item:state.item,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:1,x:state.x,y:state.y}
case 'Give_Medicine':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem-1,health:state.health+1,itemPic:null,ins:"Get a banana for your friend",item:0,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:0,x:state.x,y:state.y}
case 'AR':
return{uhl:state.uhl,talk:state.talk,gotItem:state.gotItem-1,health:state.health+1,itemPic:null,ins:"Get a banana for your friend",item:0,animal:state.animal,up:state.up,down:state.down,right:state.right,left:state.left,DRest:state.DRest,DWalk1:state.DWalk1,DWalk2:state.DWalk2,FRest:state.FRest,FWalk1:state.FWalk1,FWalk2:state.FWalk2,LRest:state.LRest,LWalk1:state.LWalk1,LWalk2:state.LWalk2,RRest:state.RRest,RWalk1:state.RWalk1,RWalk2:state.RWalk2,Tree:state.Tree,kekadu:state.DRest,Banana:state.Banana,Carrot:state.Carrot,Medicine:state.Medicine,
DBird:state.DBird,FBird:state.FBird,LBird:state.LBird,RBird:state.RBird,DDonkey:state.DDonkey,FDonkey:state.FDonkey,LDonkey:state.LDonkey,RDonkey:state.RDonkey,DMonkey:state.DMonkey,FMonkey:state.FMonkey,LMonkey:state.LMonkey,RMonkey:state.RMonkey,DRabbit:state.DRabbit,FRabbit:state.FRabbit,LRabbit:state.LRabbit,RRabbit:state.RRabbit,DFox:state.DFox,FFox:state.FFox,LFox:state.LFox,RFox:state.RFox,
BananaTree:state.BananaTree,BirdFace:state.BirdGame,DonkeyFace:state.DonkeyFace,Jungle:state.JungleBackgroundForGames,Rock:state.Rock,Paper:state.Paper,Scissor:state.Scissor,Question:state.QuestionMark,Happy:state.HappyRabbit,Hungry:state.HungryRabbit,Hit:state.HitRabbit,Thermo:state.ThermoRabbit,
BananaCount:state.BananaCount,CarrotCount:state.CarrotCount,MedicineCount:state.MedicineCount,x:304,y:state.y}}
return state}
const store=createStore(reducer)
class App extends Component{
render(){return(
<Provider store={store}>
<TabNav/>
</Provider>)}}
export default App